### ISSUE TITLE
Document strings

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/docs#113]
### Problem

We support string types but these aren't listed in the documentation anywhere I can see

example: https://github.com/noir-lang/noir/blob/master/crates/nargo_cli/tests/test_data/strings/src/main.nr

### Proposed solution

.

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by critesjosh** [comment]
strings are a compound type, correct? what methods are there on the string type? 

Is there any information that i should include that isn't demonstrated in the test you linked?

**Comment by jfecher** [comment]
> strings are a compound type, correct? what methods are there on the string type?

There are no methods on the string type. The only thing you can do with strings currently is use them with `std::println`
