### ISSUE TITLE
Document the `noirup` GitHub Action

### ISSUE THREAD

**Issue by Globallager** [noir-lang/docs#14]
- What to use it for (e.g. CI tests)
- How to use it
- Example repo

Reference: https://github.com/noir-lang/noirup#github-action

**Comment by critesjosh** [comment]
@Globallager do you know if we are using this internally for testing in any of our public repos? That would be a good reference

**Comment by Globallager** [comment]
> @Globallager do you know if we are using this internally for testing in any of our public repos? That would be a good reference

I don't think we're using it internally. @TomAFrench do share if you're aware of the GHA being used somewhere.

**Comment by TomAFrench** [comment]
I've included the github action in my merkle proof library: https://github.com/TomAFrench/noir-merkle/blob/master/.github/workflows/noir.yml

I've also got a version which is used in a repository with multiple noir projects as users will need to set the working directory to the project root: https://github.com/TomAFrench/noir-hashes/blob/master/.github/workflows/noir.yml
