### ISSUE TITLE
Missing docs for Field methods

### ISSUE THREAD

**Issue by LHerskind** [noir-lang/docs#148]
### Problem

The field methods described in https://noir-lang.org/standard_library/field_methods does not contain the full set of functions from https://github.com/noir-lang/noir/blob/master/noir_stdlib/src/field.nr

### Proposed solution

Extend the docs to include the rest of the functions

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by critesjosh** [comment]
I am not very familiar with rust, is it relevant to document [these functions](https://github.com/noir-lang/noir/blob/da473685524fc6e5e17f9c3eb95116378ac41fb8/noir_stdlib/src/field.nr#L42-L55) defined in that file? They aren't defined within `impl Field`

```rust
#[builtin(modulus_num_bits)]
fn modulus_num_bits() -> comptime Field {}

#[builtin(modulus_be_bits)]
fn modulus_be_bits() -> [u1] {}

#[builtin(modulus_le_bits)]
fn modulus_le_bits() -> [u1] {}

#[builtin(modulus_be_bytes)]
fn modulus_be_bytes() -> [u8] {}

#[builtin(modulus_le_bytes)]
fn modulus_le_bytes() -> [u8] {}
```

**Comment by critesjosh** [comment]
closed by https://github.com/noir-lang/docs/pull/149
