### ISSUE TITLE
Document how certain functions are implemented as "black box functions" and associated caveats.

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/docs#156]
### Problem

We don't flag up how certain functions in the standard library  (e.g. keccak256, ecdsa verification) are implemented as "black box functions". These are special as they rely on the backend to have support for them and backends are unlikely to support all potential black box functions.

### Proposed solution

We should add a section which describes how Noir supports these custom gates in backends to make certain computations cheaper

Main points to hit:
- Black box functions make certain zk-unfriendly computations cheaper.
- Not all backends will support a particular black box function.
  - Possible to compile noir code which won't run against a particular backend.
  - Can fallback to a less efficient implementation written in Noir/ACIR in some cases.

We should also add a link from any stdlib function which is implemented as a black box function to this page.

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by critesjosh** [comment]
Good call out @TomAFrench. 

What is the current list of black box functions?

**Comment by TomAFrench** [comment]
The list of black box functions are defined [here](https://github.com/noir-lang/acvm/blob/8b3923e191e4ac399400025496e8bb4453734040/acir/src/circuit/black_box_functions.rs#L35-L46)

You can find stdlib functions which link to these as they'll have the `#[foreign()]` modifier: https://github.com/search?q=repo%3Anoir-lang%2Fnoir%20%23%5Bforeign&type=code

You may notice there's a number of black box functions which aren't included in the stdlib as they are generated as part of the language (e.g. working with a u64 will result in RANGE black box functions being emitted to ensure you don't overflow). For these, we have fallback implementations of AND, XOR and RANGE defined in the [ACVM stdlib](https://github.com/noir-lang/acvm/blob/8b3923e191e4ac399400025496e8bb4453734040/acvm/src/compiler/transformers/fallback.rs#L69) which means that we can seamlessly fallback if the backend doesn't support them.

I'm happy to help write this btw, I was planning on doing it myself but I saw you've jumped in with a draft PR.

**Comment by critesjosh** [comment]
Thanks @TomAFrench, I will look into this. 

I'd like to document this so I have a better understanding of how Noir works. I'll put the PR together and request you as a reviewer.

**Comment by critesjosh** [comment]
Looks like [`compute_merkle_root`](https://github.com/noir-lang/noir/blob/e790c9f5da784f7617a0b578623b470af7e01116/noir_stdlib/src/merkle.nr#LL12C1-L12C32) is one that is not defined in `black_box_functions.rs` but is marked `#[foreign]`. does that count?

**Comment by TomAFrench** [comment]
We're removing the `ComputeMerkleRoot` opcode as it's more efficient to implement in Noir now according to Maxim's benchmarks. The changes in ACVM haven't filtered up to Noir yet so it's still in the stdlib.
