### ISSUE TITLE
Add how to uninstall Nargo & noirup to our docs

### ISSUE THREAD

**Issue by merfymerf** [noir-lang/docs#215]

**Comment by Savio-Sou** [comment]
Related discussions: https://github.com/noir-lang/book/pull/20

**Comment by critesjosh** [comment]
@Savio-Sou @TomAFrench 

Is the recommended way to uninstall just `rm -r ~/.nargo`?

**Comment by Savio-Sou** [comment]
> Is the recommended way to uninstall just `rm -r ~/.nargo`?

For installations via `noirup` yes, plus ~/nargo and ~/noir_cache as well I believe which contains libraries and the trusted setup SRS respectively.

For installations compiled from source, the nargo binary is located at ~/.nix-profile/bin/nargo.

P.S. speaking from what I can find locally on my machine only, might miss edge cases / installations in environments other than macOS.

**Comment by critesjosh** [comment]
Cool thanks. I'll add these general instructions to the docs
