### ISSUE TITLE
Explain why Nix is needed for Nargo installation options 3 and 4

### ISSUE THREAD

**Issue by merfymerf** [noir-lang/docs#219]
Feedback from user testing sessions.

The current instructions are unclear on why Nix is required for compiling Nargo from source through options 3 and 4.

Would be great to supplement a few sentences on how it helps manages dependencies.

**Comment by signorecello** [comment]
Looks clear enough to me:

```
**Due to the large number of native dependencies**, Noir projects uses [Nix](https://nixos.org/) and [direnv](https://direnv.net/) to streamline the development experience.
```

Will close this but I'm happy to reopen it later
