### ISSUE TITLE
add reminder to add direnv into shell in Nargo installation Option 4

### ISSUE THREAD

**Issue by merfymerf** [noir-lang/docs#220]
Feedback from Noir User Testing Program

**Comment by critesjosh** [comment]
Is the recommendation to do something more than what is covered here? https://noir-lang.org/getting_started/nargo_installation#setting-up-your-environment

![image](https://github.com/noir-lang/docs/assets/18372439/67059661-5804-4874-b53b-f8862b643da5)

**Comment by Savio-Sou** [comment]
More adding a reminder for Step 4.

The official guide linked seems to suggest running `eval "$(direnv hook bash)"` at first glance, but if read more carefully it's actually asking users to add the line in `~/.bashrc`.

User testing showed this cost devs unnecessary frustrations and time to re-read instructions.
