### ISSUE TITLE
Deprecate `--allow-warnings`; Add `--deny-warnings`

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/docs#224]
PR: https://github.com/noir-lang/noir/pull/1383

Warnings used to be treated as errors by default, where devs can opt out of the behavior with the `--allow-warnings` flag.

From v0.7.0 onwards, warnings are treated as warnings by default and the `--allow-warnings` flag is removed.

A `--deny-warnings` flag is added for opting in for treating warnings as errors.

**Comment by TomAFrench** [comment]
Just that if we have any example CI workflows shown in the docs for people to copy-paste, then we should update the flags in there to disallow warnings.
