### ISSUE TITLE
Document Noir smart contract syntaxes

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/docs#253]
As the [v0.9.0 release](https://github.com/noir-lang/noir/pull/1893) deprecates the `--experimental-ssa` flag (i.e. all Noir smart contract syntaxes would be supported out of the box), it'd be best to document the syntaxes alongside the release.

Relevant PRs:
- `contract`
  https://github.com/noir-lang/noir/issues/1135
  https://github.com/noir-lang/noir/pull/944
  https://github.com/noir-lang/noir/pull/980
- function visibilities
  https://github.com/noir-lang/noir/issues/1168
  - `open` functions
    https://github.com/noir-lang/noir/pull/1037
  - `internal` functions
    https://github.com/noir-lang/noir/pull/1873
- secret functions can have `pub` values
  https://github.com/noir-lang/noir/pull/1051

P.S. The [Aztec libraries for smart contract utilities](https://github.com/AztecProtocol/aztec-packages/tree/master/yarn-project/noir-contracts/src/libs), albeit written in Noir, are probably more suiting to be documented in Aztec's docs.

**Comment by critesjosh** [comment]
I will connect with Mike on starting this section, as it is planning to be added to the Aztec docs as well.

**Comment by Savio-Sou** [comment]
Closing as it'll be documented in the Aztec Docs instead.
