### ISSUE TITLE
Improve awareness of BigInt in docs

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/docs#271]
### Problem

The [ZK Microphone](https://github.com/Miyamura80/ZKMicrophone) suggested Noir should support `u256` and wasn't aware that the [BigInt library](https://github.com/shuklaayush/noir-bigint) exists.

### Happy Case

One approach to drive awareness could be mentioning the library in the [Data Types](https://noir-lang.org/language_concepts/data_types) page.

### Alternatives Considered

An alternative approach could be fully documenting the library.

Unsure if this is best as we might not want to maintain docs of non-stdlib libraries.

### Would you like to submit a PR for this Issue?

No

**Comment by critesjosh** [comment]
Good idea on adding this to the Data Types section. I was also thinking about linking to many of the external libraries on the landing page of the docs, since they are often of general interest.
