### ISSUE TITLE
Update comptime values example

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/docs#282]
Section: https://noir-lang.org/language_concepts/mutability/#comptime-values

Comptime values are mutable instead of immutable as currently described in the docs.

We can also furnish the section with reference to Tom's thoughts here: https://github.com/orgs/noir-lang/discussions/2002#discussioncomment-6526971

**Comment by critesjosh** [comment]
so this section is incorrect? Should I delete it?

```rust
Note that variables declared as mutable may not be comptime:

```rust
fn main() {
    // error: Cannot mark a comptime type as mutable
    let mut a: comptime Field = 5;

    // a inferred as a private Field here
    let mut a = 5;
}
```

**Comment by Savio-Sou** [comment]
Yeah, particularly "error: Cannot mark a comptime type as mutable" as I'm not getting that error from running the code.

We can also consider furnishing the section on top of Tom's thoughts linked while we're at it.
