### ISSUE TITLE
Separate Slices and Array methods

### ISSUE THREAD

**Issue by signorecello** [noir-lang/docs#302]
### Problem

Slices and Arrays are now separate again. Check Maxim's comment [here](https://github.com/noir-lang/docs/pull/255#issuecomment-1662467379) for more

### Happy Case

In practice we should separate documentation for Arrays and Slices in the stdlib section and mention the `as_slice` method that converts arrays to slices

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Duplicate of https://github.com/noir-lang/docs/issues/284?
