### ISSUE TITLE
Move "Language Server" page out from "Getting Started"

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/docs#349]
### Problem

The easiest path to make use of Noir's Language Server Protocol features is installing the plug-and-play [Noir Language Support VS Code Extension](https://marketplace.visualstudio.com/items?itemName=noir-lang.vscode-noir).

The "Language Server" page is likely most useful to devs that would like to build non-VS-Code Noir IDE tooling, which sounds out of scope of the "Getting Started" section.

### Happy Case

I don't really have a strong opinion. Some options could be moving it to:
- A standalone page / section, or
- A new "Tooling" section, or
- A new "Advanced" section

### Would you like to submit a PR for this Issue?

No

**Comment by signorecello** [comment]
Maybe moving it to the "Nargo" section? Tbh I wouldn't move it for now, but I understand your reasoning

**Comment by critesjosh** [comment]
I agree we should move it. I think it makes more sense to go in the Nargo section than the Getting Started section, especially since the LSP uses nargo under the hood. No one who's just getting started is going to care about how the LSP works.
