### ISSUE TITLE
Add "Examples" Section

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/docs#36]
- After "Coming Features" section
- Move "Merkle Proof" into this
- Add a "ZK Battleships" page

**Comment by signorecello** [comment]
@Globallager did the first two points already, but I'm hesitant on adding ZK Battleships here, as it would make us also document every other project using Noir... I'm assuming the documentation of these projects is a requirement of the projects themselves

**Comment by Globallager** [comment]
Suggested BattleZips more for having >1 examples in the section, not necessarily documenting every Noir projects.

Do you have any suggestions if not BZ?

For BZ btw we could directly copy-paste content from their [README](https://github.com/BattleZips/BattleZips-Noir/blob/main/README.md) (agreed with Mach 34 already on such rights of use).

**Comment by signorecello** [comment]
as part of docs 2.0, we will gradually have more time to document our own examples (ex. stealth drop), so I'm closing this for the time being
