### ISSUE TITLE
Document `noir_js`

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/docs#371]
```[tasklist]
### Helpful Prerequisite
- [ ] https://github.com/noir-lang/noir/issues/2711
```

The new _noir_js_ is [now released on NPM](https://www.npmjs.com/package/@noir-lang/noir_js). It would be great to update the TypeScript page and describe how to make use of the Noir.js JavaScript package.

### Additional Context

_noir_js_ is currently a wrapper for _acvm_js_ and _noirc_abi_wasm_. _acvm_js_ is used for Noir program execution (i.e. witness generation) and _noirc_abi_wasm_ is a helper for encoding initial witness in preparation for execution / witness generation. 

The [compile_prove_verify.test.ts](https://github.com/noir-lang/noir/blob/5a3fb60140561ef0504cb86bd297d48eae82bf3b/compiler/integration-tests/test/integration/browser/compile_prove_verify.test.ts) is a great reference for how to make use of _noir_js_.

**Comment by Savio-Sou** [comment]
@signorecello closed with https://github.com/noir-lang/docs/pull/393?

**Comment by signorecello** [comment]
indeed
