### ISSUE TITLE
Review "Dependencies" Page

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/docs#49]
- Supplement example
  - https://github.com/kevaundray/hello-world-noir is outdated
  - Specify file to modify (i.e. `Nargo.toml`)

**Comment by signorecello** [comment]
@Globallager the example is broken, is this still relevant? if so, could we get more information on it?

**Comment by Globallager** [comment]
Feel free to use whatever repo as an example 🙌 Goal is to demonstrate how dependencies are managed, that's all.

**Comment by SleepingShell** [comment]
@signorecello It would be useful to specify that ``dep::`` must prefix the specified dependency name in ``Nargo.toml``. Had to trial and error this myself to figure that out.

**Comment by critesjosh** [comment]
@SleepingShell I updated this in https://github.com/noir-lang/docs/pull/164

**Comment by SleepingShell** [comment]
@critesjosh thank you! I recently came upon this issue, which suggests that local paths can be included as well? And that it will correctly work for modules of a crate? This would also be useful information on the page.

https://github.com/noir-lang/noir/pull/1034

**Comment by SleepingShell** [comment]
@critesjosh I hope #165 is good!

**Comment by critesjosh** [comment]
> @critesjosh I hope #165 is good!

perfect. thank you!
