### ISSUE TITLE
Document usage of elliptic curve primitives

### ISSUE THREAD

**Issue by Globallager** [noir-lang/docs#82]
Corresponding PR: https://github.com/noir-lang/noir/pull/964

To be documented under the _Noir Standard Library_ section.

The inlined comments in the PR might be helpful to facilitate understanding, but if it's too technical we can simply document it as "it exists!" for now.

Last doc issue for v0.3.2.

**Comment by critesjosh** [comment]
added via this pr (https://github.com/noir-lang/docs/pull/89)
